# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9df40d36792824543a526565b2f4cfa7ff66dc59ec55c1a3919816a9a1327482d46b0ba473877f1bfdb273aaa549322e5b8f885f1314dd67811ff82b0908b4df

test:
  secret_key_base: 2b95031371b4c0ad003af7caa8436f858404db6a814204c7def61286de382bf343b21f3eb82b76e1ca92219676647083903aaf5a746723a76b18c27dfecdea12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
